# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
#Section.create({ name: 'Intro' })
#Section.create({ name: 'Verse' })
#Section.create({ name: 'PreChorus' })
#Section.create({ name: 'Chorus' })
#Section.create({ name: 'Bridge' })
#Section.create({ name: 'Break' })
#Section.create({ name: 'Solo' })
#Section.create({ name: 'Outro' })

#MusicalNote.create({ name: 'C' })
#MusicalNote.create({ name: 'C#' })
#MusicalNote.create({ name: 'Db' })
#MusicalNote.create({ name: 'D' })
#MusicalNote.create({ name: 'D#' })
#MusicalNote.create({ name: 'Eb' })
#MusicalNote.create({ name: 'E' })
#MusicalNote.create({ name: 'F' })
#MusicalNote.create({ name: 'F#' })
#MusicalNote.create({ name: 'Gb' })
#MusicalNote.create({ name: 'G' })
#MusicalNote.create({ name: 'G#' })
#MusicalNote.create({ name: 'Ab' })
#MusicalNote.create({ name: 'A' })
#MusicalNote.create({ name: 'A#' })
#MusicalNote.create({ name: 'Bb' })
#MusicalNote.create({ name: 'B' })
#MusicalNote.create({ name: 'C' })
#MusicalNote.create({ name: '%' })

  puts "      💥"

#MusicalScale.create({ name: 'M' })
#MusicalScale.create({ name: 'M7' })
#MusicalScale.create({ name: 'M9' })
#MusicalScale.create({ name: 'M11' })
#MusicalScale.create({ name: 'M13' })
#MusicalScale.create({ name: 'm' })
#MusicalScale.create({ name: 'm7' })
#MusicalScale.create({ name: 'm9' })
#MusicalScale.create({ name: 'm11' })
#MusicalScale.create({ name: 'm13' })
#MusicalScale.create({ name: '7' })
#MusicalScale.create({ name: '9' })
#MusicalScale.create({ name: '11' })
#MusicalScale.create({ name: '13' })
#MusicalScale.create({ name: 'aug' })
#MusicalScale.create({ name: 'aug7' })
#MusicalScale.create({ name: 'aug9' })
#MusicalScale.create({ name: 'aug11' })
#MusicalScale.create({ name: 'aug13' })
#MusicalScale.create({ name: 'dim' })
#MusicalScale.create({ name: 'dim7' })
#MusicalScale.create({ name: 'dim9' })
#MusicalScale.create({ name: 'dim b9' })
#MusicalScale.create({ name: 'dim11' })
#MusicalScale.create({ name: 'aug maj9' })
#MusicalScale.create({ name: 'aug maj11' })
#MusicalScale.create({ name: 'aug maj13' })
#MusicalScale.create({ name: 'ø9' })
#MusicalScale.create({ name: 'øb9' })
#MusicalScale.create({ name: 'ø11' })
#MusicalScale.create({ name: 'ø13' })
#MusicalScale.create({ name: ' ' })


  puts "      💥"

#Type.create({ name: 'Single' })
#Type.create({ name: 'Couple' })
#Type.create({ name: '1rst half Single, then Couple' })
#Type.create({ name: '1rst half Couple, then Single' })
#Type.create({ name: 'Four' })

#SecondMusicalNote.create({ name: 'C' })
#SecondMusicalNote.create({ name: 'C#' })
#SecondMusicalNote.create({ name: 'Db' })
#SecondMusicalNote.create({ name: 'D' })
#SecondMusicalNote.create({ name: 'D#' })
#SecondMusicalNote.create({ name: 'Eb' })
#SecondMusicalNote.create({ name: 'E' })
#SecondMusicalNote.create({ name: 'F' })
#SecondMusicalNote.create({ name: 'F#' })
#SecondMusicalNote.create({ name: 'Gb' })
#SecondMusicalNote.create({ name: 'G' })
#SecondMusicalNote.create({ name: 'G#' })
#SecondMusicalNote.create({ name: 'Ab' })
#SecondMusicalNote.create({ name: 'A' })
#SecondMusicalNote.create({ name: 'A#' })
#SecondMusicalNote.create({ name: 'Bb' })
#SecondMusicalNote.create({ name: 'B' })
#SecondMusicalNote.create({ name: 'C' })
#SecondMusicalNote.create({ name: '%' })

  puts "      💥"

#SecondMusicalScale.create({ name: 'M' })
#SecondMusicalScale.create({ name: 'M7' })
#SecondMusicalScale.create({ name: 'M9' })
#SecondMusicalScale.create({ name: 'M11' })
#SecondMusicalScale.create({ name: 'M13' })
#SecondMusicalScale.create({ name: 'm' })
#SecondMusicalScale.create({ name: 'm7' })
#SecondMusicalScale.create({ name: 'm9' })
#SecondMusicalScale.create({ name: 'm11' })
#SecondMusicalScale.create({ name: 'm13' })
#SecondMusicalScale.create({ name: '5' })
#SecondMusicalScale.create({ name: '7' })
#SecondMusicalScale.create({ name: '9' })
#SecondMusicalScale.create({ name: '11' })
#SecondMusicalScale.create({ name: '13' })
#SecondMusicalScale.create({ name: 'aug' })
#SecondMusicalScale.create({ name: 'aug7' })
#SecondMusicalScale.create({ name: 'aug9' })
#SecondMusicalScale.create({ name: 'aug11' })
#SecondMusicalScale.create({ name: 'aug13' })
#SecondMusicalScale.create({ name: 'dim' })
#SecondMusicalScale.create({ name: 'dim7' })
#SecondMusicalScale.create({ name: 'dim9' })
#SecondMusicalScale.create({ name: 'dim b9' })
#SecondMusicalScale.create({ name: 'dim11' })
#SecondMusicalScale.create({ name: 'aug maj9' })
#SecondMusicalScale.create({ name: 'aug maj11' })
#SecondMusicalScale.create({ name: 'aug maj13' })
#SecondMusicalScale.create({ name: 'ø9' })
#SecondMusicalScale.create({ name: 'øb9' })
#SecondMusicalScale.create({ name: 'ø11' })
#SecondMusicalScale.create({ name: 'ø13' })
#SecondMusicalScale.create({ name: ' ' })


#ThirdMusicalNote.create({ name: 'C' })
#ThirdMusicalNote.create({ name: 'C#' })
#ThirdMusicalNote.create({ name: 'Db' })
#ThirdMusicalNote.create({ name: 'D' })
#ThirdMusicalNote.create({ name: 'D#' })
#ThirdMusicalNote.create({ name: 'Eb' })
#ThirdMusicalNote.create({ name: 'E' })
#ThirdMusicalNote.create({ name: 'F' })
#ThirdMusicalNote.create({ name: 'F#' })
#ThirdMusicalNote.create({ name: 'Gb' })
#ThirdMusicalNote.create({ name: 'G' })
#ThirdMusicalNote.create({ name: 'G#' })
#ThirdMusicalNote.create({ name: 'Ab' })
#ThirdMusicalNote.create({ name: 'A' })
#ThirdMusicalNote.create({ name: 'A#' })
#ThirdMusicalNote.create({ name: 'Bb' })
#ThirdMusicalNote.create({ name: 'B' })
#ThirdMusicalNote.create({ name: 'C' })
#ThirdMusicalNote.create({ name: '%' })

  puts "      💥"

#ThirdMusicalScale.create({ name: 'M' })
#ThirdMusicalScale.create({ name: 'M7' })
#ThirdMusicalScale.create({ name: 'M9' })
#ThirdMusicalScale.create({ name: 'M11' })
#ThirdMusicalScale.create({ name: 'M13' })
#ThirdMusicalScale.create({ name: 'm' })
#ThirdMusicalScale.create({ name: 'm7' })
#ThirdMusicalScale.create({ name: 'm9' })
#ThirdMusicalScale.create({ name: 'm11' })
#ThirdMusicalScale.create({ name: 'm13' })
#ThirdMusicalScale.create({ name: '5' })
#ThirdMusicalScale.create({ name: '7' })
#ThirdMusicalScale.create({ name: '9' })
#ThirdMusicalScale.create({ name: '11' })
#ThirdMusicalScale.create({ name: '13' })
#ThirdMusicalScale.create({ name: 'aug' })
#ThirdMusicalScale.create({ name: 'aug7' })
#ThirdMusicalScale.create({ name: 'aug9' })
#ThirdMusicalScale.create({ name: 'aug11' })
#ThirdMusicalScale.create({ name: 'aug13' })
#ThirdMusicalScale.create({ name: 'dim' })
#ThirdMusicalScale.create({ name: 'dim7' })
#ThirdMusicalScale.create({ name: 'dim9' })
#ThirdMusicalScale.create({ name: 'dim b9' })
#ThirdMusicalScale.create({ name: 'dim11' })
#ThirdMusicalScale.create({ name: 'aug maj9' })
#ThirdMusicalScale.create({ name: 'aug maj11' })
#ThirdMusicalScale.create({ name: 'aug maj13' })
#ThirdMusicalScale.create({ name: 'ø9' })
#ThirdMusicalScale.create({ name: 'øb9' })
#ThirdMusicalScale.create({ name: 'ø11' })
#ThirdMusicalScale.create({ name: 'ø13' })
#ThirdMusicalScale.create({ name: ' ' })


#FourthMusicalNote.create({ name: 'C' })
#FourthMusicalNote.create({ name: 'C#' })
#FourthMusicalNote.create({ name: 'Db' })
#FourthMusicalNote.create({ name: 'D' })
#FourthMusicalNote.create({ name: 'D#' })
#FourthMusicalNote.create({ name: 'Eb' })
#FourthMusicalNote.create({ name: 'E' })
#FourthMusicalNote.create({ name: 'F' })
#FourthMusicalNote.create({ name: 'F#' })
#FourthMusicalNote.create({ name: 'Gb' })
#FourthMusicalNote.create({ name: 'G' })
#FourthMusicalNote.create({ name: 'G#' })
#FourthMusicalNote.create({ name: 'Ab' })
#FourthMusicalNote.create({ name: 'A' })
#FourthMusicalNote.create({ name: 'A#' })
#FourthMusicalNote.create({ name: 'Bb' })
#FourthMusicalNote.create({ name: 'B' })
#FourthMusicalNote.create({ name: 'C' })
#FourthMusicalNote.create({ name: '%' })


  puts "      💥"

#FourthMusicalScale.create({ name: 'M' })
#FourthMusicalScale.create({ name: 'M7' })
#FourthMusicalScale.create({ name: 'M9' })
#FourthMusicalScale.create({ name: 'M11' })
#FourthMusicalScale.create({ name: 'M13' })
#FourthMusicalScale.create({ name: 'm' })
#FourthMusicalScale.create({ name: 'm7' })
#FourthMusicalScale.create({ name: 'm9' })
#FourthMusicalScale.create({ name: 'm11' })
#FourthMusicalScale.create({ name: 'm13' })
#FourthMusicalScale.create({ name: '5' })
#FourthMusicalScale.create({ name: '7' })
#FourthMusicalScale.create({ name: '9' })
#FourthMusicalScale.create({ name: '11' })
#FourthMusicalScale.create({ name: '13' })
#FourthMusicalScale.create({ name: 'aug' })
#FourthMusicalScale.create({ name: 'aug7' })
#FourthMusicalScale.create({ name: 'aug9' })
#FourthMusicalScale.create({ name: 'aug11' })
#FourthMusicalScale.create({ name: 'aug13' })
#FourthMusicalScale.create({ name: 'dim' })
#FourthMusicalScale.create({ name: 'dim7' })
#FourthMusicalScale.create({ name: 'dim9' })
#FourthMusicalScale.create({ name: 'dim b9' })
#FourthMusicalScale.create({ name: 'dim11' })
#FourthMusicalScale.create({ name: 'aug maj9' })
#FourthMusicalScale.create({ name: 'aug maj11' })
#FourthMusicalScale.create({ name: 'aug maj13' })
#FourthMusicalScale.create({ name: 'ø9' })
#FourthMusicalScale.create({ name: 'øb9' })
#FourthMusicalScale.create({ name: 'ø11' })
#FourthMusicalScale.create({ name: 'ø13' })
#FourthMusicalScale.create({ name: ' ' })

#Instrument.create({ name: "Basse" })
#Instrument.create({ name: "Batterie" })
#Instrument.create({ name: "Chant lead" })
#Instrument.create({ name: "Choeurs" })
#Instrument.create({ name: "Guitare" })
#Instrument.create({ name: "Keyboards" })
#Instrument.create({ name: "Trombone" })
#Instrument.create({ name: "Machines" })
#Instrument.create({ name: "Trompette" })
#Instrument.create({ name: "Banjo" })
#Instrument.create({ name: "Yukulélé" })
#Instrument.create({ name: "Flûte traversière" })
#Instrument.create({ name: "Clarinette" })
#Instrument.create({ name: "Saxophone" })
#Instrument.create({ name: "Violon" })
#Instrument.create({ name: "Contrebasse" })
#Instrument.create({ name: "Accordéon" })

#Genre.create({ name: 'Blues' })
#Genre.create({ name: 'Country' })
#Genre.create({ name: 'Disco' })
#Genre.create({ name: 'Electro' })
#Genre.create({ name: 'Funk' })
#Genre.create({ name: 'Gospel' })
#Genre.create({ name: 'Jazz' })
#Genre.create({ name: 'Métal' })
#Genre.create({ name: 'Musica Latina' })
#Genre.create({ name: 'Pop' })
#Genre.create({ name: 'Rap' })
#Genre.create({ name: 'Reggae' })
#Genre.create({ name: 'Rock' })
#Genre.create({ name: 'Salsa' })
#Genre.create({ name: 'Soul' })

  puts "      💥"

