# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
#Section.create({ name: 'Intro' })
#Section.create({ name: 'Verse' })
#Section.create({ name: 'PreChorus' })
#Section.create({ name: 'Chorus' })
#Section.create({ name: 'Bridge' })
#Section.create({ name: 'Break' })
#Section.create({ name: 'Solo' })
#Section.create({ name: 'Outro' })
  puts "      💥"

#MusicalNote.create({ name: 'C' })
#MusicalNote.create({ name: 'C#/Db' })
#MusicalNote.create({ name: 'D' })
#MusicalNote.create({ name: 'D#/Eb' })
#MusicalNote.create({ name: 'E' })
#MusicalNote.create({ name: 'F' })
#MusicalNote.create({ name: 'F#/Gb' })
#MusicalNote.create({ name: 'G' })
#MusicalNote.create({ name: 'G#/Ab' })
#MusicalNote.create({ name: 'A' })
#MusicalNote.create({ name: 'A#/Bb' })
#MusicalNote.create({ name: 'B' })
#MusicalNote.create({ name: 'C' })
  puts "      💥"

#MusicalScale.create({ name: 'Major' })
#MusicalScale.create({ name: 'maj7' })
#MusicalScale.create({ name: 'maj9' })
#MusicalScale.create({ name: 'maj11' })
#MusicalScale.create({ name: 'maj13' })
#MusicalScale.create({ name: 'maj9#11' })
#MusicalScale.create({ name: 'maj13#11' })
#MusicalScale.create({ name: '6' })
#MusicalScale.create({ name: 'add9' })
#MusicalScale.create({ name: '6add9' })
#MusicalScale.create({ name: 'maj7b5' })
#MusicalScale.create({ name: 'maj7#5' })
#MusicalScale.create({ name: 'Minor' })
#MusicalScale.create({ name: 'm7' })
#MusicalScale.create({ name: 'm9' })
#MusicalScale.create({ name: 'm11' })
#MusicalScale.create({ name: 'm13' })
#MusicalScale.create({ name: 'm6' })
#MusicalScale.create({ name: 'madd9' })
#MusicalScale.create({ name: 'm6add9' })
#MusicalScale.create({ name: 'mmaj7' })
#MusicalScale.create({ name: 'mmaj9' })
#MusicalScale.create({ name: 'm7b5' })
#MusicalScale.create({ name: 'm7#5' })
#MusicalScale.create({ name: '7' })
#MusicalScale.create({ name: '9' })
#MusicalScale.create({ name: '11' })
#MusicalScale.create({ name: '13' })
#MusicalScale.create({ name: '7sus4' })
#MusicalScale.create({ name: '7b5' })
#MusicalScale.create({ name: '7#5' })
#MusicalScale.create({ name: '7b9' })
#MusicalScale.create({ name: '7#9' })
#MusicalScale.create({ name: '7(b5,b9)' })
#MusicalScale.create({ name: '7(b5,#9)' })
#MusicalScale.create({ name: '7(#5,b9)' })
#MusicalScale.create({ name: '7(#5,#9)' })
#MusicalScale.create({ name: '9b5' })
#MusicalScale.create({ name: '9#5' })
#MusicalScale.create({ name: '13#11' })
#MusicalScale.create({ name: '13b9' })
#MusicalScale.create({ name: '11b9' })
#MusicalScale.create({ name: 'aug' })
#MusicalScale.create({ name: 'dim' })
#MusicalScale.create({ name: 'dim7' })
#MusicalScale.create({ name: '5' })
#MusicalScale.create({ name: 'sus4' })
#MusicalScale.create({ name: 'sus2' })
#MusicalScale.create({ name: 'sus2sus4' })
#MusicalScale.create({ name: '-5' })

  puts "      💥"

Type.create({ name: 'Single' })
Type.create({ name: 'Couple' })
Type.create({ name: '1rst half Single, then Couple' })
Type.create({ name: '1rst half Couple, then Single' })
Type.create({ name: 'Four' })

